version: 0.2

env:
  variables:
      AWS_REGION: "ap-southeast-1"
      ARCHITECTURE: "amd64"
phases:
  install:
    runtime-versions:
       java: corretto17
  pre_build:
    commands:
       - mvn clean install
       - echo "loggin ECR"
       - aws --version
       - aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 747610744334.dkr.ecr.ap-southeast-1.amazonaws.com
  build:
    commands:
       - docker build -t sample-service .
  post_build:
    commands:
       - docker tag sample-service:latest 747610744334.dkr.ecr.ap-southeast-1.amazonaws.com/sample-service:latest
       - docker push 747610744334.dkr.ecr.ap-southeast-1.amazonaws.com/sample-service:latest
